module.exports = {
	sanomaConsentCategories: [],
	getContentDeeplink: false,
	urls: ["http://www.google.nl", "http://www.google.com", "http://www.facebook.com", "http://www.youtube.com", "http://www.wikipedia.org", "http://www.linkedin.com", "http://www.live.com", "http://www.twitter.com", "http://www.marktplaats.nl", "http://www.nu.nl", "http://www.yahoo.com", "http://www.telegraaf.nl", "http://www.ing.nl", "http://www.bol.com", "http://www.amazon.com", "http://www.rabobank.nl", "http://www.imdb.com", "http://www.instagram.com", "http://www.blogspot.nl", "http://www.msn.com", "http://www.nos.nl", "http://www.abnamro.nl", "http://www.dumpert.nl", "http://www.ad.nl", "http://www.tweakers.net", "http://www.kat.cr", "http://www.stackoverflow.com", "http://www.wordpress.com", "http://www.reddit.com", "http://www.xvideos.com", "http://www.diply.com", "http://www.buienradar.nl", "http://www.funda.nl", "http://www.bing.com", "http://www.imgur.com", "http://www.paypal.com", "http://www.pinterest.com", "http://www.apple.com", "http://www.geenstijl.nl", "http://www.weeronline.nl", "http://www.tumblr.com", "http://www.viralmundo.nl", "http://www.pornhub.com", "http://www.xhamster.com", "http://www.vkmag.com", "http://www.microsoft.com", "http://www.aliexpress.com", "http://www.booking.com", "http://www.beslist.nl", "http://www.powned.tv", "http://www.netflix.com", "http://www.amazon.de", "http://www.ebay.com", "http://www.wehkamp.nl", "http://www.bbc.com", "http://www.volkskrant.nl", "http://www.vice.com", "http://www.ah.nl", "http://www.amazon.co.uk", "http://www.nrc.nl", "http://www.npo.nl", "http://www.ns.nl", "http://www.adobe.com", "http://www.xcams.com", "http://www.soundcloud.com", "http://www.9gag.com", "http://www.belastingdienst.nl", "http://www.dropbox.com", "http://www.voetbalzone.nl", "http://www.postnl.nl", "http://www.fok.nl", "http://www.digid.nl", "http://www.startpagina.nl", "http://www.rtlnieuws.nl", "http://www.theguardian.com", "http://www.vk.com", "http://www.mediamarkt.nl", "http://www.google.de", "http://www.ask.com", "http://www.zalando.nl", "http://www.ziggo.nl", "http://www.xnxx.com", "http://www.google.co.uk", "http://www.tvgids.nl", "http://www.ikea.com", "http://www.9292.nl", "http://www.wikia.com", "http://www.anwb.nl", "http://www.ebay.nl", "http://www.stackexchange.com", "http://www.kvk.nl", "http://www.dailymail.co.uk", "http://www.redtube.com", "http://www.debijenkorf.nl", "http://www.kieskeurig.nl", "http://www.vi.nl", "http://www.koopplein.nl", "http://www.indeed.nl", "http://www.youporn.com"],	
	zoomFactor: 1,
	userAgent: 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0',
	viewportSize: {width: 1280, height: 1024},
	clipRect: {top: 0, left: 0, width: 1280, height: 1024},
	screenshotPage: true,
	detectBanners: false,
	storeCookies: true,
	trackResources: true,
	trackErrors: true
};