//['atinternet', 'ads', 'stats', 'functional', 'interests', 'stir', 'social', 'videoplaza'];

module.exports = {
    detectParty: detectParty
};

// Create function which tries to identify the party of a specific cookie
function detectParty(location, cookie_site, cookie_name) {
	checks = [
		{"value": cookie_site,		"regexp": "krxd", 					"party": "Krux",						"type": "interests"},
		{"value": cookie_site, 		"regexp": "xiti",					"party": "AT Internet",					"type": "stats"},
		{"value": cookie_site, 		"regexp": "adform", 				"party": "Adform",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "meetrics", 				"party": "Meetrics",					"type": "stats"},
		{"value": cookie_site, 		"regexp": "adtech", 				"party": "AdTech",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "adscience", 				"party": "AdScience",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "doubleclick", 			"party": "DoubleClick",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "yieldlab", 				"party": "Yieldlab",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "mediaplex", 				"party": "Mediaplex",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "angsrvr", 				"party": "Falk Technologies",			"type": "ads"},
		{"value": cookie_site, 		"regexp": "adsrvr", 				"party": "TheTradeDesk",				"type": "ads"},
		{"value": cookie_site, 		"regexp": "casalemedia", 			"party": "Casale Media",				"type": "ads"},
		{"value": cookie_site, 		"regexp": "mookie1", 				"party": "Media Innovation Group",		"type": "ads"},
		{"value": cookie_site, 		"regexp": "skimresources", 			"party": "Skimlinks",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "rifhub", 				"party": "Rook Media",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "snapwidget", 			"party": "SnapWidget (Instagram)",		"type": "social"},
		{"value": cookie_site, 		"regexp": "gwallet", 				"party": "RadiumOne",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "rlcdn",	 				"party": "RapLeaf (TowerData)",			"type": "stats"},
		{"value": cookie_site, 		"regexp": "agkn.com",	 			"party": "Neustar Inc.",				"type": "interests"},
		{"value": cookie_site, 		"regexp": "smartclip",	 			"party": "SmartClip",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "tapad",	 				"party": "Tapad",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "vimeo",	 				"party": "Vimeo",						"type": ""},
		{"value": cookie_site, 		"regexp": "instansive",	 			"party": "Instansive (Instagram)",		"type": "social"},
		{"value": cookie_site, 		"regexp": "videoplaza",	 			"party": "Videoplaza",					"type": "videoplaza"},
		{"value": cookie_site, 		"regexp": "lijit",	 				"party": "Federated Media Publishing",	"type": "ads"},
		{"value": cookie_site, 		"regexp": "atemda",	 				"party": "AdMeta AB",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "contextweb",	 			"party": "Pulsepoint (Contextweb)",		"type": "ads"},
		{"value": cookie_site, 		"regexp": "pubmatic",				"party": "PutMatic",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "stickyadstv",			"party": "StickyAds",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "flx1",					"party": "Flxpxl",						"type": "interest"},
		{"value": cookie_site, 		"regexp": "criteo", 				"party": "Criteo",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "rubiconproject",			"party": "Rubicon",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "bidswitch", 				"party": "Bidswitch",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "scorecardresearch", 		"party": "ScoreCard Research",			"type": "stats"},
		{"value": cookie_site,		"regexp": "serving-sys", 			"party": "Sizmek",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "openx", 					"party": "OpenX",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "adnxs.com", 				"party": "AppNexus",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "de17a", 					"party": "Delta Projects",				"type": "ads"},
		{"value": cookie_site, 		"regexp": "weborama", 				"party": "Weborama",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "crwdcntrl", 				"party": "Lotame",						"type": "stats"},
		{"value": cookie_site, 		"regexp": "sitestat.com", 			"party": "Sitestat (ComScore)",			"type": "stats"},
		{"value": cookie_site, 		"regexp": "nr-data", 				"party": "New Relic",					"type": "stats"},
		{"value": cookie_site, 		"regexp": "liverail", 				"party": "LiveRail",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "demdex", 				"party": "Media Optimizer (Adobe)",		"type": "ads"},
		{"value": cookie_site, 		"regexp": "adscale", 				"party": "AdScale",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "ibillboard", 			"party": "Internet Billboard",			"type": "ads"},
		{"value": cookie_site, 		"regexp": "nexac", 					"party": "Datalogix",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "bidtheatre", 			"party": "BidTheatre",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "livechatinc", 			"party": "LiveChat Inc.",				"type": "functional"},
		{"value": cookie_site, 		"regexp": "wtp101", 				"party": "Digilant",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "adaptv", 				"party": "Adap.tv",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "addthis", 				"party": "AddThis",						"type": "social"},
		{"value": cookie_site, 		"regexp": "sharethis", 				"party": "ShareThis",					"type": "social"},
		{"value": cookie_site, 		"regexp": "adadvisor", 				"party": "Neustar AdAdvisor",			"type": "interests"},
		{"value": cookie_site, 		"regexp": "yahoo", 					"party": "Yahoo",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "dotomi", 				"party": "Dotomi",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "eyeota", 				"party": "Eyeota",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "adrcntr", 				"party": "Adrime (Weborama)",			"type": "ads"},
		{"value": cookie_site, 		"regexp": "revsci", 				"party": "AudienceScience",				"type": "ads"},
		{"value": cookie_site, 		"regexp": "creative-serving", 		"party": "Platform 161",				"type": "ads"},
		{"value": cookie_site, 		"regexp": "bidswitch", 				"party": "IPONWEB",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "bing.com", 				"party": "Bing",						"type": "social"},
		{"value": cookie_site, 		"regexp": "spotify.com", 			"party": "Spotify",						"type": "social"},
		{"value": cookie_site, 		"regexp": "smartadserver", 			"party": "SMART Advserver",				"type": "ads"},
		{"value": cookie_site, 		"regexp": "spotxchange", 			"party": "SpotXchange",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "mathtag", 				"party": "MediaMath",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "254a", 					"party": "Yieldr",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "ad-serverparc", 			"party": "Adlantic",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "2cnt.net", 				"party": "BARB",						"type": "interests"},
		{"value": cookie_site, 		"regexp": "pinterest", 				"party": "Pinterest",					"type": "social"},
		{"value": cookie_site, 		"regexp": "turn", 					"party": "Turn Inc.",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "youtube", 				"party": "Youtube",						"type": "social"},
		{"value": cookie_site, 		"regexp": "twitter", 				"party": "Twitter",						"type": "social"},
		{"value": cookie_site,	 	"regexp": "360yield.com", 			"party": "Improve Digital",				"type": "ads"},
		{"value": cookie_site,	 	"regexp": "google.com", 			"party": "Google",						"type": "ads"},
		{"value": cookie_name,		"regexp": "^__insp_", 				"party": "Brightcrove",					"type": "ads"},
		{"value": cookie_name,		"regexp": "chartbeat", 				"party": "Chartbeat",					"type": "stats"},
		{"value": cookie_name, 		"regexp": "(session|sess|ss)-?id",	"party": "Site-own",					"type": "functional"},
		{"value": cookie_name, 		"regexp": "SanomaWeb",				"party": "Site-own",					"type": "functional"},
		{"value": cookie_name, 		"regexp": "sanoma", 				"party": "Sanoma",						"type": "ads"},
		{"value": cookie_name,		"regexp": "^__utm[a-z]{1}", 		"party": "Google Analytics",			"type": "stats"},
		{"value": cookie_name,		"regexp": "^_gat?", 				"party": "Google Analytics",			"type": "stats"},
		{"value": cookie_name, 		"regexp": "^__gads", 				"party": "Google Adsense",				"type": "ads"},
		{"value": cookie_name, 		"regexp": "^_vis_opt", 				"party": "Visual Website Optimiser",	"type": "stats"},
		{"value": cookie_name, 		"regexp": "consentbarviewcount",	"party": "Sanoma Consent Manager",		"type": "functional"},
		{"value": cookie_name, 		"regexp": "site_consent",			"party": "Sanoma Consent Manager",		"type": "functional"},
		{"value": cookie_site, 		"regexp": "bluekai", 				"party": "Bluekai",						"type": "interests"},
		{"value": cookie_site, 		"regexp": "rfihub", 				"party": "RFI Hub",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "media6degrees", 			"party": "Media6Degrees",				"type": "interests"},
		{"value": cookie_site, 		"regexp": "adsymptotic", 			"party": "AdSymptotic",					"type": "ads"},
		{"value": cookie_site, 		"regexp": "twimg",		 			"party": "Twimg",						"type": "social"},
		{"value": cookie_site, 		"regexp": "msn",		 			"party": "MSN",							"type": "ads"},
		{"value": cookie_site, 		"regexp": "ligatus",		 		"party": "Ligatus",						"type": "ads"},
		{"value": cookie_site, 		"regexp": "bloglovin",		 		"party": "Blog Lovin",					"type": "social"},
		{"value": cookie_site, 		"regexp": "addtoany",		 		"party": "AddToAny",					"type": "social"},
		{"value": cookie_site, 		"regexp": "cookie.monster",		 	"party": "Monsterboard",				"type": "interests"},
		{"value": cookie_site, 		"regexp": "gigya",		 			"party": "Gigya",						"type": "interests"},
		{"value": cookie_site, 		"regexp": "intercomcdn",		 	"party": "InterCom",					"type": "interests"},
		{"value": cookie_site, 		"regexp": "pagefair",		 		"party": "PageFair",					"type": "stats"},
		{"value": location.host, 	"regexp": cookie_site, 				"party": "Site-own",					"type": ""},
		{"value": cookie_site, 		"regexp": location.host, 			"party": "Site-own",					"type": ""}		
	];
	
	for (x in checks) {
		regexp = new RegExp(checks[x].regexp.toLowerCase());
		if (regexp.test(checks[x].value.toLowerCase()))
			return {"party": checks[x].party, "type": checks[x]['type']};
	}
	
	return {"party": "", "type": ""};
}

