
module.exports = {
        rules: [		{"name_regexp":"","location_regexp":"eyeota","operator":"1","rule_type":"1","company_name":"Eyeota","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"youtube","operator":"1","rule_type":"1","company_name":"Youtube","consent_type":"social"},
		{"name_regexp":"","location_regexp":"twitter","operator":"1","rule_type":"1","company_name":"Twitter","consent_type":"social"},
		{"name_regexp":"","location_regexp":"360yield.com","operator":"1","rule_type":"1","company_name":"Improve Digital","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"google.com","operator":"1","rule_type":"1","company_name":"Google","consent_type":"ads"},
		{"name_regexp":"^__insp_","location_regexp":"","operator":"1","rule_type":"1","company_name":"Brightcrove","consent_type":"ads"},
		{"name_regexp":"chartbeat","location_regexp":"","operator":"1","rule_type":"1","company_name":"Chartbeat","consent_type":"stats"},
		{"name_regexp":"(session|sess|ss)-?id","location_regexp":"","operator":"1","rule_type":"1","company_name":"Site-owned","consent_type":"functional"},
		{"name_regexp":"SanomaWeb","location_regexp":"","operator":"1","rule_type":"1","company_name":"Site-owned","consent_type":"functional"},
		{"name_regexp":"^__utm[a-z]{1}","location_regexp":"","operator":"1","rule_type":"1","company_name":"Google Analytics","consent_type":"stats"},
		{"name_regexp":"^_gat?","location_regexp":"","operator":"1","rule_type":"1","company_name":"Google Analytics","consent_type":"stats"},
		{"name_regexp":"^__gads","location_regexp":"","operator":"1","rule_type":"1","company_name":"Google Adsense","consent_type":"ads"},
		{"name_regexp":"^_vis_opt","location_regexp":"","operator":"1","rule_type":"1","company_name":"Visual Website Optimizer","consent_type":"stats"},
		{"name_regexp":"","location_regexp":"turn","operator":"1","rule_type":"1","company_name":"Turn Inc.","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"pinterest","operator":"1","rule_type":"1","company_name":"Pinterest","consent_type":"social"},
		{"name_regexp":"","location_regexp":"adrcntr","operator":"1","rule_type":"1","company_name":"Adrime (Weborama)","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"revsci","operator":"1","rule_type":"1","company_name":"AudienceScience","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"creative-serving","operator":"1","rule_type":"1","company_name":"Platform 161","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"bidswitch","operator":"1","rule_type":"1","company_name":"IPONWEB","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"bing.com","operator":"1","rule_type":"1","company_name":"Bing","consent_type":"social"},
		{"name_regexp":"","location_regexp":"spotify.com","operator":"1","rule_type":"1","company_name":"Spotify","consent_type":"social"},
		{"name_regexp":"","location_regexp":"smartadserver","operator":"1","rule_type":"1","company_name":"SMART Advserver","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"spotxchange","operator":"1","rule_type":"1","company_name":"SpotXchange","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"mathtag","operator":"1","rule_type":"1","company_name":"MediaMath","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"254a","operator":"1","rule_type":"1","company_name":"Yieldr","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"ad-serverparc","operator":"1","rule_type":"1","company_name":"Adlantic","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"2cnt.net","operator":"1","rule_type":"1","company_name":"BARB","consent_type":"interests"},
		{"name_regexp":"consentBarViewCount","location_regexp":"","operator":"1","rule_type":"1","company_name":"Sanoma Consent Manager","consent_type":"functional"},
		{"name_regexp":"site_consent","location_regexp":"","operator":"1","rule_type":"1","company_name":"Sanoma Consent Manager","consent_type":"functional"},
		{"name_regexp":"","location_regexp":"cts\\.snmmd\\.nl\\\/lib\\\/js\\\/advertising\\.js","operator":"1","rule_type":"2","company_name":"Sanoma Adblock Checker","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"googleadservices.com\/pagead\/conversion.js","operator":"1","rule_type":"2","company_name":"Google Adwords","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"hotjar","operator":"1","rule_type":"2","company_name":"Hotjar","consent_type":"stats"},
		{"name_regexp":"","location_regexp":"adform","operator":"1","rule_type":"2","company_name":"Adform","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"ytimg","operator":"1","rule_type":"2","company_name":"Youtube","consent_type":"social"},
		{"name_regexp":"","location_regexp":"youtube","operator":"1","rule_type":"2","company_name":"Youtube","consent_type":"social"},
		{"name_regexp":"","location_regexp":"visualwebsiteoptimizer.com","operator":"1","rule_type":"2","company_name":"Visual Website Optimizer","consent_type":"stats"},
		{"name_regexp":"","location_regexp":"connect.facebook.net","operator":"1","rule_type":"2","company_name":"Facebook Connect","consent_type":"interests"},
		{"name_regexp":"","location_regexp":"sprinkle","operator":"1","rule_type":"2","company_name":"Sprinkle","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"twitter","operator":"1","rule_type":"2","company_name":"Twitter","consent_type":"social"},
		{"name_regexp":"","location_regexp":"blendle","operator":"1","rule_type":"2","company_name":"Blendle","consent_type":"interests"},
		{"name_regexp":"","location_regexp":"instagram","operator":"1","rule_type":"2","company_name":"Instragram","consent_type":"social"},
		{"name_regexp":"^optimizely","location_regexp":"","operator":"1","rule_type":"1","company_name":"Optimizely","consent_type":"stats"},
		{"name_regexp":"","location_regexp":"pagefair","operator":"1","rule_type":"1","company_name":"PageFair","consent_type":"stats"},
		{"name_regexp":"","location_regexp":"bluekai","operator":"1","rule_type":"1","company_name":"Bluekai","consent_type":"interests"},
		{"name_regexp":"","location_regexp":"rfihub","operator":"1","rule_type":"1","company_name":"RFI Hub","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"media6degrees","operator":"1","rule_type":"1","company_name":"Media6Degrees","consent_type":"interests"},
		{"name_regexp":"","location_regexp":"adsymptotic","operator":"1","rule_type":"1","company_name":"AdSymptotic","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"twimg","operator":"1","rule_type":"1","company_name":"Twimg","consent_type":"social"},
		{"name_regexp":"","location_regexp":"msn","operator":"1","rule_type":"1","company_name":"MSN","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"ligatus","operator":"1","rule_type":"1","company_name":"Ligatus","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"bloglovin","operator":"1","rule_type":"1","company_name":"Blog Lovin","consent_type":"social"},
		{"name_regexp":"","location_regexp":"addtoany","operator":"1","rule_type":"1","company_name":"AddToAny","consent_type":"social"},
		{"name_regexp":"","location_regexp":"cookie.monster","operator":"1","rule_type":"1","company_name":"Monsterboard","consent_type":"interests"},
		{"name_regexp":"","location_regexp":"gigya","operator":"1","rule_type":"1","company_name":"Gigya","consent_type":"interests"},
		{"name_regexp":"","location_regexp":"intercomcdn","operator":"1","rule_type":"1","company_name":"InterCom","consent_type":"interests"},
		{"name_regexp":"","location_regexp":"\\\/consent\\.js","operator":"1","rule_type":"2","company_name":"Sanoma Consent Manager","consent_type":"functional"},
		{"name_regexp":"","location_regexp":"krx","operator":"1","rule_type":"1","company_name":"Krux","consent_type":"interests"},
		{"name_regexp":"","location_regexp":"snapwidget","operator":"1","rule_type":"1","company_name":"SnapWidget (Instagram)","consent_type":"social"},
		{"name_regexp":"","location_regexp":"gwallet","operator":"1","rule_type":"1","company_name":"RadiumOne","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"rlcdn","operator":"1","rule_type":"1","company_name":"RapLeaf (TowerData)","consent_type":"stats"},
		{"name_regexp":"","location_regexp":"agkn.com","operator":"1","rule_type":"1","company_name":"Neustar Inc.","consent_type":"interests"},
		{"name_regexp":"","location_regexp":"smartclip","operator":"1","rule_type":"1","company_name":"SmartClip","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"tapad","operator":"1","rule_type":"1","company_name":"Tapad","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"vimeo","operator":"1","rule_type":"1","company_name":"Vimeo","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"instansive","operator":"1","rule_type":"1","company_name":"Instansive (Instagram)","consent_type":"social"},
		{"name_regexp":"","location_regexp":"videoplaza","operator":"1","rule_type":"1","company_name":"Videoplaza","consent_type":"videoplaza"},
		{"name_regexp":"","location_regexp":"lijit","operator":"1","rule_type":"1","company_name":"Federated Media Publishing","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"atemda","operator":"1","rule_type":"1","company_name":"AdMeta AB","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"contextweb","operator":"1","rule_type":"1","company_name":"Pulsepoint (Contextweb)","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"rifhub","operator":"1","rule_type":"1","company_name":"Rook Media","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"skimresources","operator":"1","rule_type":"1","company_name":"Skimlinks","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"xiti","operator":"1","rule_type":"1","company_name":"AT Internet","consent_type":"stats"},
		{"name_regexp":"","location_regexp":"adform","operator":"1","rule_type":"1","company_name":"Adform","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"meetrics","operator":"1","rule_type":"1","company_name":"Meetrics","consent_type":"stats"},
		{"name_regexp":"","location_regexp":"adtech","operator":"1","rule_type":"1","company_name":"AdTech","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"adscience","operator":"1","rule_type":"1","company_name":"AdScience","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"doubleclick","operator":"1","rule_type":"1","company_name":"DoubleClick","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"yieldlab","operator":"1","rule_type":"1","company_name":"Yieldlab","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"mediaplex","operator":"1","rule_type":"1","company_name":"Mediaplex","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"angsrvr","operator":"1","rule_type":"1","company_name":"Falk Technologies","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"adsrvr","operator":"1","rule_type":"1","company_name":"TheTradeDesk","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"casalemedia","operator":"1","rule_type":"1","company_name":"Casale Media","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"mookie1","operator":"1","rule_type":"1","company_name":"Media Innovation Group","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"pubmatic","operator":"1","rule_type":"1","company_name":"PubMatic","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"stickyadstv","operator":"1","rule_type":"1","company_name":"StickyAds","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"flx1","operator":"1","rule_type":"1","company_name":"Flxpxl","consent_type":"interests"},
		{"name_regexp":"","location_regexp":"demdex","operator":"1","rule_type":"1","company_name":"Media Optimizer (Adobe)","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"adscale","operator":"1","rule_type":"1","company_name":"AdScale","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"ibillboard","operator":"1","rule_type":"1","company_name":"Internet Billboard","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"nexac","operator":"1","rule_type":"1","company_name":"Datalogix","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"bidtheatre","operator":"1","rule_type":"1","company_name":"BidTheatre","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"livechatinc","operator":"1","rule_type":"1","company_name":"LiveChat Inc.","consent_type":"functional"},
		{"name_regexp":"","location_regexp":"wtp101","operator":"1","rule_type":"1","company_name":"Digilant","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"adaptv","operator":"1","rule_type":"1","company_name":"Adap.tv","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"addthis","operator":"1","rule_type":"1","company_name":"AddThis","consent_type":"social"},
		{"name_regexp":"","location_regexp":"sharethis","operator":"1","rule_type":"1","company_name":"ShareThis","consent_type":"social"},
		{"name_regexp":"","location_regexp":"adadvisor","operator":"1","rule_type":"1","company_name":"Neustar AdAdvisor","consent_type":"interests"},
		{"name_regexp":"","location_regexp":"yahoo","operator":"1","rule_type":"1","company_name":"Yahoo","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"liverail","operator":"1","rule_type":"1","company_name":"LiveRail","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"nr-data","operator":"1","rule_type":"1","company_name":"New Relic","consent_type":"stats"},
		{"name_regexp":"","location_regexp":"criteo","operator":"1","rule_type":"1","company_name":"Criteo","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"rubiconproject","operator":"1","rule_type":"1","company_name":"Rubicon","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"bidswitch","operator":"1","rule_type":"1","company_name":"Bidswitch","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"scorecardresearch","operator":"1","rule_type":"1","company_name":"ScoreCard Research","consent_type":"stats"},
		{"name_regexp":"","location_regexp":"serving-sys","operator":"1","rule_type":"1","company_name":"Sizmek","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"openx","operator":"1","rule_type":"1","company_name":"OpenX","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"adnxs.com","operator":"1","rule_type":"1","company_name":"AppNexus","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"de17a","operator":"1","rule_type":"1","company_name":"Delta Projects","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"weborama","operator":"1","rule_type":"1","company_name":"Weborama","consent_type":"ads"},
		{"name_regexp":"","location_regexp":"crwdcntrl","operator":"1","rule_type":"1","company_name":"Lotame","consent_type":"stats"},
		{"name_regexp":"","location_regexp":"sitestat.com","operator":"1","rule_type":"1","company_name":"Sitestat (ComScore)","consent_type":"stats"},
		{"name_regexp":"","location_regexp":"dotomi","operator":"1","rule_type":"1","company_name":"Dotomi","consent_type":"ads"},
		{"name_regexp":"sanoma","location_regexp":"","operator":"1","rule_type":"1","company_name":"Sanoma","consent_type":"ads"}

        ]
};
